apiVersion: v1
kind: ConfigMap
metadata:
  name:  scheduler-config
  namespace: {{ .Values.scheduler.namespace }}
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta3
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
    - schedulerName: moirai-scheduler
      plugins:
        multiPoint:
          enabled:
          - name: moirai
        queueSort:
          enabled:
          - name: moirai
          disabled:
          - name: '*'
      pluginConfig:
      - name: moirai
        args:
          name: moirai

