kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.controller.name }}
  namespace: {{ .Values.controller.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.controller.name }}
    app.kubernetes.io/instance: {{ .Values.controller.name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: moirai
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.controller.name }}
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.controller.name }}
        app.kubernetes.io/component: controller
    spec:
      serviceAccount: moirai-controller
      containers:
      - name: {{ .Values.controller.name }}
        image: {{ .Values.controller.image }}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
        name: {{ .Values.scheduler.name }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.scheduler.name }}
    app.kubernetes.io/instance: {{ .Values.scheduler.name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: scheduler
    app.kubernetes.io/part-of: moirai
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  name: {{ .Values.scheduler.name }}
  namespace: {{ .Values.scheduler.namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.scheduler.name }}
      app.kubernetes.io/component: scheduler
  replicas: {{ .Values.scheduler.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.scheduler.name }}
        app.kubernetes.io/component: scheduler
    spec:
      serviceAccountName: moirai-scheduler
      containers:
      - command:
        - /scheduler
        - --config=/etc/kubernetes/scheduler-config.yaml
        image: {{ .Values.scheduler.image }}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10259
            scheme: HTTPS
          initialDelaySeconds: 15
        name: {{ .Values.scheduler.name }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10259
            scheme: HTTPS
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
        securityContext:
          privileged: false
        volumeMounts:
        - name: scheduler-config
          mountPath: /etc/kubernetes
          readOnly: true
      hostNetwork: false
      hostPID: false
      volumes:
      - name: scheduler-config
        configMap:
          name: scheduler-config
