# permissions for end users to view queuebindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: queuebinding-viewer-role
rules:
- apiGroups:
  - scheduling.moirai.io
  resources:
  - queuebindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scheduling.moirai.io
  resources:
  - queuebindings/status
  verbs:
  - get
