apiVersion: batch/v1
kind: Job
metadata:
  name: sample-job
  labels:
    moirai.io/queue: sample-queue
spec:
  template:
    spec:
      schedulerName: moirai-scheduler
      containers:
      - name: pi
        image: perl
        command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(2000)"]
        resources:
          requests:
            cpu: 1
            memory: "100Mi"
          limits:
            cpu: 1
            memory: "100Mi"
      restartPolicy: Never
