apiVersion: batch/v1
kind: Job
metadata:
  name: sample-job
  labels:
    moirai.io/queue: sample-queue
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        moirai.io/queue-binding: queuebinding-sample-job
    spec:
      schedulerName: moirai-scheduler
      containers:
      - name: pi
        image: perl:5.34
        command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(2000)"]
        resources:
          requests:
            cpu: "1"
            memory: "100Mi"
          limits:
            cpu: "1"
            memory: "100Mi"
      restartPolicy: Never
