apiVersion: scheduling.moirai.io/v1alpha1
kind: QueueBinding
metadata:
  name: queuebinding-sample
spec:
  queue: "queue-sample"
  PriorityClassName: "batch"
  resources:
    cpu: 1
    memory: 500Mi
  jobRef:
