apiVersion: kubescheduler.config.k8s.io/v1beta3
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: false
clientConnection:
  kubeconfig: /Users/rudeigerc/.kube/config
profiles:
- schedulerName: moirai-scheduler
  plugins:
    multiPoint:
      enabled:
      - name: moirai
    queueSort:
      enabled:
      - name: moirai
      disabled:
      - name: '*'
  pluginConfig:
  - name: moirai
    args:
      name: moirai
