apiVersion: kubescheduler.config.k8s.io/v1beta3
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: false
clientConnection:
  kubeconfig: /Users/rudeigerc/.kube/config
profiles:
  - schedulerName: moirai-scheduler
    plugins:
      multiPoint:
        enabled:
        - name: moirai
